# Generated by Django 3.2.25 on 2025-11-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
