# Generated by Django 3.2.25 on 2025-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20251116_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('logement', models.CharField(choices=[('Maison', 'Maison'), ('Studio', 'Studio'), ('1 pièce', '1 pièce'), ('2-3 pièces', '2-3 pièces'), ('Appartement', 'Appartement')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
