# Generated by Django 3.2.25 on 2025-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_demandedevis'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedevis',
            name='telephone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
